spring:
  application:
    name: javaray
  datasource:
    url: jdbc:oracle:thin:@61.37.177.140:1521:xe
    username: JAVARAY
    password: JAVARAY
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      enabled: true
      max-file-size: 60MB
      max-request-size: 65MB

server:
  port: 80
  tomcat:
    max-http-form-post-size: 65MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: NULL
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kh.javaray.member.model.dto com.kh.javaray.token.model.dto com.kh.javaray.shipping.shippings.model.dto com.kh.javaray.shipping.dto com.kh.javaray.shipping.review.model.dto com.kh.javaray.shipping.dto com.kh.javaray.shipping.book.model.dto com.kh.javaray.funding.model.dto com.kh.javaray.funding.businessinfo.model.dto 

logging:
  level:
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.resultest: DEBUG
    jdbc.audit: DEBUG

jwt:
  secret: H7oIaBujRo6fA/a0wdk09iY6STECQZbemMj8bcs5xBMzd0IYxzT+hNQd+fgXvsyz3qHF3DIwuYXUE9m7w5tkDw==
