spring:
  application:
    name: javaray
  datasource:
    url: jdbc:oracle:thin:@61.37.177.140:1521:xe
    username: JAVARAY
    password: JAVARAY
    driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 80
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: NULL
  mapper-locations: classpath:mapper/*.xml