DROP TABLE TB_FISH;
CREATE TABLE TB_FISH(
	FISH_NO VARCHAR2(5) PRIMARY KEY,
	FISH_NAME VARCHAR2(60) NOT NULL UNIQUE
);

DROP TABLE TB_FISH_CONTENT;
CREATE TABLE TB_FISH_CONTENT(
	FISH_NO VARCHAR2(5) REFERENCE TB_FISH PRIMARY KEY,
	START_OUT_OF_SEASON DATE,
	END_OUT_OF_SEASON DATE,
	DEFAULT_SIZE NUMBER,
	EXPLAINATION VARCHAR2(1500) NOT NULL
);

DROP TABLE TB_SERVICE
CREATE TABLE TB_SERVICE(
	SHIPPING_SERVIE_NO NUMBER PRIMARY KEY;
	SHIPPING_SERVICE_CONTENT VARCHAR2(60) NOT NULL UNIQUE
)

DROP TABLE TB_SHIPPING_IMAGE;
CREATE TABLE TB_SHIPPING)IMAGE(
	IMAGE_NO NUMBER PRIMARY KEY,
	IMAGE_PATH VARCHAR2(60) NOT NULL,
	IMAGE_ORIGIN_NAME VARCHAR2(60) NOT NULL,
	IMAGE_CHANGE_NAME VARCHAR2(60) NOT NULL UNIQUE,
	REF_BOARD_NO VARCHAR2(60) NOT NULL,
	IMAGE_LEVEL CHAR(1) NOT NULL,
	STATUS CHAR(1) NOT NULL
);

DROP TABLE TB_PORT;
CREATE TABLE TB_PORT(
	PORT_NO VARVHAR2(5) PRIMARY KEY,
	LAT NUMBER NOT NULL,
	LON NUMBER NOT NULL,
	ADDRESS VARCHAR2(150) NOT NULL
);


