DROP TABLE TB_FISH;
CREATE TABLE TB_FISH(
	FISH_NO VARCHAR2(5) PRIMARY KEY,
	FISH_NAME VARCHAR2(60) NOT NULL UNIQUE
);

DROP TABLE TB_FISH_CONTENT;
CREATE TABLE TB_FISH_CONTENT(
	FISH_NO VARCHAR2(5) REFERENCE TB_FISH PRIMARY KEY,
	START_OUT_OF_SEASON DATE,
	END_OUT_OF_SEASON DATE,
	DEFAULT_SIZE NUMBER,
	EXPLAINATION VARCHAR2(1500) NOT NULL
);

DROP TABLE TB_SERVICE
CREATE TABLE TB_SERVICE(
	SHIPPING_SERVIE_NO NUMBER PRIMARY KEY;
	SHIPPING_SERVICE_CONTENT VARCHAR2(60) NOT NULL UNIQUE
)

DROP TABLE TB_SHIPPING_IMAGE;
CREATE TABLE TB_SHIPPING)IMAGE(
	IMAGE_NO NUMBER PRIMARY KEY,
	IMAGE_PATH VARCHAR2(60) NOT NULL,
	IMAGE_ORIGIN_NAME VARCHAR2(60) NOT NULL,
	IMAGE_CHANGE_NAME VARCHAR2(60) NOT NULL UNIQUE,
	REF_BOARD_NO VARCHAR2(60) NOT NULL,
	IMAGE_LEVEL CHAR(1) NOT NULL,
	STATUS CHAR(1) NOT NULL
);

DROP TABLE TB_PORT;
CREATE TABLE TB_PORT(
	PORT_NO VARVHAR2(5) PRIMARY KEY,
	LAT NUMBER NOT NULL,
	LON NUMBER NOT NULL,
	ADDRESS VARCHAR2(150) NOT NULL
);

DROP TABLE TB_LICENSE;
CREATE TABLE TB_LICENSE(
	FISHING_NO NUMBER REFERENCE TB_FISHING PRIMARY KEY,
	ORIGIN_NAME VARCHAR2(200),
	CHANGE_NAME VARCHAR2(200),
	FILE_PATH VARCHAR2(100),
	FILE_LEVEL NUMBER
);

DROP TABLE TB_PROHIBIT_AREA;
CREATE TABLE TB_PROHIBIT_AREA(
	PROHIBIT_AREA_NO NUMBER PRIMARY KEY,
	PROHIBIT_AREA_NAME VARCHAR2(100) NOT NULL UNIQUE,
	PROHIBIT_AREA_SPOT VARCHAR2(500) UNIQUE
);

DROP TABLE TB_LIMIT_AREA;
CREATE TABLE TB_LIMIT_AREA(
	LIMIT_AREA_NO NUMBER PRIMARY KEY,
	LIMIT_AREA_NAME VARCHAR2(100) NOT NULL UNIQUE,
	LIMIT_AREA_SPOT VARCHAR2(500)
);

DROP TABLE TB_FISHING_PRODUCT;
CREATE TABLE TB_FISHING_PRODUCT(
	PRODUCT_NO NUMBER NOT NULL PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(300),
	PRICE NUMBER
);

DROP TABLE TB_REGISTERED_FISHING_PRODUCT;
CREATE TABLE TB_REGISTERED_FISHING_PRODUCT(
	PRODUCT_NO NUMBER REFERENCE TB_FISHING_PRODUCT,
	FISHING_NO NUMBER REFERENCE TB_FISHING,
	PRIMARY KEY(PRODUCT_NO, FISHING_NO)
);

DROP TABLE TB_RESERVATION;
CREATE TABLE TB_RESERVATION(
	REV_NO NUMBER PRIMARY KEY,
	PRODUCT_NO NUMBER NOT NULL REFERENCE TB_FISHING_PRODUCT,
	USER_NO NUMBER NOT NULL REFERENCE TB_MEMBER,
	PERSONNEL NUMBER NOT NULL,
	FISHING_DATE VARCHAR2(30) NOT NULL,
	REV_DATE VARCHAR2(30) NOT NULL DEFAULT SYSDATE,
	MODIFY_DATE VARCHAR2(30),
	STATUS CHAR(1) NOT NULL DEFAULT 'N' CHECK(STATUS IN('N', 'Y'))
);

DROP TABLE TB_REV_CANCEL;
CREATE TABLE TB_REV_CANCEL(
	CANCEL_NO NUMBER PRIMARY KEY,
	REV_NO NUMBER NOT NULL REFERENCE TB_RESERVATION,
	CANCEL_COMMENT VARCHAR2(200) NOT NULL,
	CANCEL_DATE DATE NOT NULL DEFAULT SYSDATE
);

DROP TABLE TB_REVIEW;
CREATE TABLE TB_REVIEW(
	REVIEW_NO NUMBER PRIMARY KEY,
	REV_NO NUMBER NOT NULL REFERENCE TB_RESERVATION,
	USER_NO NUMBER NOT NULL REFERENCE TB_MEMBER,
	CREATED_DATE DATE NOT NULL DEFAULT SYSDATE,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	STATUS CHAR(1) NOT NULL DEFAULT 'N' CHECK(STATUS IN ('N', 'Y'))
);

DROP TABLE TB_REVIEW_PHOTO;
CREATE TABLE TB_REVIEW_PHOTO(
	FILE_NO NUMBER PRIMARY KEY,
	REVIEW_NO NUMBER NOT NULL REFERENCE TB_REVIEW,
	ORIGIN_NAME VARCHAR2(200),
	CHANGE_NAME VARCHAR2(200),
	FILE_PATH VARCHAR2(200),
	FILE_LEVEL NUMBER
);

DROP TABLE TB_SOCIAL_USER;
CREATE TABLE TB_SOCIAL_USER(
	SOCIAL_ID NUMBER PRIMARY KEY,
	USER_NO NUMBER NOT NULL REFERENCE TB_MEMBER,
	SOCIAL_CODE VARCHAR2(50) NOT NULL,
	PROFILE_IMAGE VARCHAR2(1000) NOT NULL,
	CREATE_AT DATE NOT NULL DEFAULT SYSDATE
);

DROP TABLE TB_TOKEN;
CREATE TABLE TB_TOKEN(
	USER_NO NUMBER NOT NULL REFERENCE TB_MEMBER,
	REFRESH_TOKEN VARCHAR2(500) NOT NULL,
	EXPIRED_AT NUMBER NOT NULL
);

DROP TABLE TB_USER_PROFILE;
CREATE TABLE TB_USER_PROFILE(
	PROFILR_NO NUMBER PRIMARY KEY,
	USER_NO NUMBER NOT NULL REFERENCE TB_MEMBER,
	CHANGE_NAME VARCHAR2(100),
	PATH VARCHAR2(100),
	STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN ('N', 'Y'))
);


DROP TABLE TB_CHAT_ROOM;
CREATE TABLE TB_CHAT_ROOM(
	ROOM_NO NUMBER PRIMARY KEY,
	ROOM_NAME VARCHAR2(255) NOT NULL,
	USER_NO NUMBER NOT NULL REFERENCE TB_MEMBER,
	ROOM_PWD VARCHAR2(50),
	STATUS CHAR(1) NOT NULL DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N'))
);

DROP TABLE TB_CHAT_MESSAGE;
CREATE TABLE TB_CHAT_MESSAGE(
	PARTICIPANT_NO NUMBER PRIMARY KEY,
	ROOM_NO NUMBER NOT NULL REFERENCE TB_CHAT_ROOM,
	USER_NO NUMBER NOT NULL REFERENCE TB_MEMBER,
	JOIN_AT VARCHAR2(50) NOT NULL DEFAULT SYSDATE
);

DROP TABLE TB_CHAT_ALARM;
CREATE TABLE TB_CHAT_ALARM(
	ALARM_NO NUMBER PRIMARY KEY,
	ROOM_NO NUMBER NOT NULL REFERENCE TB_CHAT_ROOM,
	USER_NO NUMBER NOT NULL REFERENCE TB_MEMBER,
	JOINED_AT DATE NOT NULL DEFAULT SYSDATE,
	UNREAD_COUNT VARCHAR2(500) NOT NULL,
	UPDATEED_AT DATE DEFAULT SYSDATE
);

